import Head from "next/head";
import Link from "next/link";

import dbConnect from "../lib/dbConnect";
import Movie from "../models/Movie";

const Home = ({ movies }) => (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container ">
        <h1 className="font-light text-4xl mb-2">Movies T</h1>
        <Link href="/new" >
          <div className="bg-movies-blue text-white text-base mx-auto rounded text-center py-2 px-2">Agregar+</div>
        </Link>
        {movies.map(({ _id, title, plot }) => (
          <div className="card mb-2" key={_id}>
            <div className="font-bold text-xl">
              <div className="h5 uppercase mb-2">{title}</div>
              <p className="font-light text-base  mb-4">{plot}</p>
              <Link href={`/${_id}`}>
               
                <div className="bg-movies-green text-white text-sm rounded text-center py-2 px-2">
                Más info...
          </div>
              </Link>
            </div>
          </div>
        ))}
      </main>
    </>
  );

export async function getServerSideProps() {
  try {
    await dbConnect();

    const result = await Movie.find({})

    const movies = result.map((doc) => {
      const movie = doc.toObject();
      movie._id = `${movie._id.toString()}`;
      return movie;
    });

    return { props: { movies } };
  } catch (error) {
    console.log(error);
  }
}

export default Home